name: Pre-commit

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencie3
        run: |
          pip install pre-commit -c constraints.txt
        shell: bash
      - name: pre-commit
        run: |
          pre-commit run --all-files
